---
title: "Boy or Girl Paradox"
author: "Zifan Lin"
date: "March 5, 2015"
output: html_document
---

The **Boy or Girl Paradox** dates back to at least 1959, when [Martin Gardner](http://en.wikipedia.org/wiki/Martin_Gardner) published one of the earlist variants of the paradox in *Scientific American*.

Titled *The Two Children Problem*, he phrased the paradox as follows:

- Mr.Jones has two children. The order child is a girl. What is the probability that both children are girls?
- Mr.Smith has two children. At least one of them is a boy. What is the probability that both children are boys?

Assumptions:

1. Each child is either male or female. 
2. Each child has the same chance of being male and female.
3. The sex of each child is independent of the sex of the other.


Gardner initially gave the answers $\frac{1}{2}$ and $\frac{1}{3}$, respectively; but later acknowledged that the second question was ambiguous. Its answer could be $\frac{1}{2}$ or $\frac{1}{3}$, depending on how you found out that one child was a boy.

- For the first question, there are four possible outcomes: {GG}, {GB}, {BG}, {BB}. Only two of these meet the criteria specified in the question: {GG}, {GB}. The probability of the event {GG} is $\frac{1}{2}$.

- For the second question, it is ambiguous. Gardner argued that a "failure to specify the randomizing procedure" could lead readers to interpret the question in two distinct ways:
    - From all families with two children, at least one of whom is a boy (i.e. {GB}, {BG}, {BB}), a family is chosen at random. This would yield the answer of $\frac{1}{3}$.
    $$Pr(BB|ALOB) = \frac{Pr(ALOB|BB) Pr(BB)}{Pr(ALOB)}= \frac{1\times \frac{1}{4}}{\frac{3}{4}}= \frac{1}{3}$$
    - From all families with two children, one child is selected at random, and the sex of that child is specified to be a boy. The other child could be either boy or girl. This would yield an answer of $\frac{1}{2}$.
    $$Pr(BB|SampleIsB) = \frac{Pr(SampleIsB|BB) Pr(BB)}{Pr(SampleIsB)} = \frac{1\times \frac{1}{4}}{\frac{1}{2}}= \frac{1}{2}$$