---
title: "Monty Hall Problem"
author: "Zifan Lin"
date: "March 3, 2015"
output: html_document
---
### Description
The **Monty Hall Problem** is a famous probability puzzel, loosly based on the American television game show *Let's Make a Deal* and name after its original host, Monty Hall.

- Suppose you are given the choice of three doors: behind one door is a car (prize), the other two goats(loose). You pick a door, say No.1, and the host, who knows what's behind the doors, opens another door, say No.3, which has a goat. You now have a chance to switch to door No.2. Is it to your advantage to switch your choice?

There are many other variants about this problem. I'll talk about it later.

### Solution

Most people initially think not to switch the door, since each door has the same probability to win the car $\frac{1}{3}$, and switch will not increase the probability. However, it is not true - it will definitely increase the probability to $\frac{2}{3}$ because the host gives you more information.

The probability logic is: At the beginning, you have the probability $\frac{1}{3}$ to choose the right door, and in this case switch will let you loose the prize. You have the probability $\frac{2}{3}$ to choose the door with a goat, and in this case the host must open the door with another goat, if now you switch the door, you will certainly win the car. Overall, if you choose to switch, the probability to win the car is $\frac{2}{3}$.

